In [1]:
import numpy as np
import pandas as pd

In [2]:
array1 = np.arange(12)
array2 = array1.reshape(2, 3, 2)
print(array2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [3]:
linspaceArray = np.linspace(0, 20, 6)
print(linspaceArray)

[ 0.  4.  8. 12. 16. 20.]


In [4]:
linspaceArrayCopy = linspaceArray.copy()
print(linspaceArrayCopy)

[ 0.  4.  8. 12. 16. 20.]


In [35]:
a1 = np.array([[25, 16]])
a2 = np.array([[11, 2], [13, 4]])
a3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a1, a2, a3))

sortedArray = np.sort(newArray)
print(sortedArray)

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [57]:
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

combineArray = np.concatenate((one, two, three))
comboArray = np.sort(combineArray)
print(comboArray)

print(comboArray[1])
print(comboArray[2:])
print(comboArray[3:13])
print(comboArray[-6:])
print(comboArray[-24:])
print(comboArray[16::2])

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[20 22 24 26]


In [60]:
col1 = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
col2 = pd.Series([4, 3, 2, 1], name='Quantity')
col3 = pd.Series(["cups", "cup", "large", "can"], name='Unit')

df = pd.concat([col1, col2, col3], axis=1)
df

Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         3    cup
2        Eggs         2  large
3        Spam         1    can

In [68]:
studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

df = pd.DataFrame(studentData)
df

desertList = ["ice cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
df['Dessert'] = desertList
df

sortedStudentData = df.sort_values(by=['Name', 'address'], ascending=True)
sortedStudentData

Name  Height Qualification  address  Age        Pets           sport  \
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       Waffles  
0     ice cream  
1  Cashew Fudge

In [69]:
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df

df.to_csv('cows_and_goats.csv', index=False)


In [76]:
data = {'Vegtable': ["Carrot", "Spinach", "Potato"], 'Color': ["Orange", "Green", "Brown"]}
veggies = pd.DataFrame(data)
veggies

veggies.to_csv('veggies.csv', index=False)



In [78]:
df = pd.read_csv('veggies.csv')
df.rename(columns={'Vegtable': 'Veggie'}, inplace=True)
df
df.to_csv('veggiesNewName.csv', index=False)